# Railway.app configuration
# https://docs.railway.app/guides/config-as-code

[build]
builder = "nixpacks"

[deploy]
startCommand = "node index.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

# Healthcheck
[deploy.healthcheck]
path = "/health"
timeout = 100
interval = 10
